"use strict";(self.webpackChunkwebpacktest=self.webpackChunkwebpacktest||[]).push([[250],{9250:(e,r,t)=>{var o;t.d(r,{UO:()=>h});var n=t(7294);const a="function"==typeof Object.is?Object.is:function(e,r){return e===r&&(0!==e||1/e==1/r)||e!=e&&r!=r},{useState:s,useEffect:c,useLayoutEffect:i,useDebugValue:u}=o||(o=t.t(n,2));function d(e){const r=e.getSnapshot,t=e.value;try{const e=r();return!a(t,e)}catch(e){return!0}}"undefined"==typeof window||void 0===window.document||window.document.createElement,(o||(o=t.t(n,2))).useSyncExternalStore;const l=n.createContext({outlet:null,matches:[]});function h(){let{matches:e}=n.useContext(l),r=e[e.length-1];return r?r.params:{}}class p extends n.Component{constructor(e){super(e),this.state={location:e.location,error:e.error}}static getDerivedStateFromError(e){return{error:e}}static getDerivedStateFromProps(e,r){return r.location!==e.location?{error:e.error,location:e.location}:{error:e.error||r.error,location:r.location}}componentDidCatch(e,r){console.error("React Router caught the following error during render",e,r)}render(){return this.state.error?React.createElement(RouteErrorContext.Provider,{value:this.state.error,children:this.props.component}):this.props.children}}var f,g;!function(e){e.UseRevalidator="useRevalidator"}(f||(f={})),function(e){e.UseLoaderData="useLoaderData",e.UseActionData="useActionData",e.UseRouteError="useRouteError",e.UseNavigation="useNavigation",e.UseRouteLoaderData="useRouteLoaderData",e.UseMatches="useMatches",e.UseRevalidator="useRevalidator"}(g||(g={}));var v;!function(e){e[e.pending=0]="pending",e[e.success=1]="success",e[e.error=2]="error"}(v||(v={}));new Promise((()=>{}));class m extends n.Component{constructor(e){super(e),this.state={error:null}}static getDerivedStateFromError(e){return{error:e}}componentDidCatch(e,r){console.error("<Await> caught the following error during render",e,r)}render(){let{children:e,errorElement:r,resolve:t}=this.props,o=null,n=v.pending;if(t instanceof Promise)if(this.state.error){v.error;let e=this.state.error;Promise.reject().catch((()=>{})),Object.defineProperty(o,"_tracked",{get:()=>!0}),Object.defineProperty(o,"_error",{get:()=>e})}else t._tracked?(t,void 0!==o._error?v.error:void 0!==o._data?v.success:v.pending):(v.pending,Object.defineProperty(t,"_tracked",{get:()=>!0}),t.then((e=>Object.defineProperty(t,"_data",{get:()=>e})),(e=>Object.defineProperty(t,"_error",{get:()=>e}))));else v.success,Promise.resolve(),Object.defineProperty(o,"_tracked",{get:()=>!0}),Object.defineProperty(o,"_data",{get:()=>t});if(n===v.error&&o._error instanceof AbortedDeferredError)throw neverSettledPromise;if(n===v.error&&!r)throw o._error;if(n===v.error)return React.createElement(AwaitContext.Provider,{value:o,children:r});if(n===v.success)return React.createElement(AwaitContext.Provider,{value:o,children:e});throw o}}}}]);